name: deckdeckgo-handler
maintainer: Nicolas Mattia <nicolas@nmattia.com>
copyright: (c) 2019 David Dal Busco and Nicolas Mattia
license: AGPL-3

dependencies:
    - aeson
    - amazonka
    - amazonka-dynamodb
    - base
    - lens
    - random
    - servant
    - servant-server
    - text
    - unliftio
    - unordered-containers
    - wai-cors
    - wai-lambda

ghc-options:
    - -Wall

executable:
    main: Main.hs
