name: deckdeckgo-handler
maintainer: Nicolas Mattia <nicolas@nmattia.com>
copyright: (c) 2019 David Dal Busco and Nicolas Mattia
license: AGPL-3

dependencies:
    - aeson
    - base
    - servant
    - servant-server
    - wai-lambda

ghc-options:
    - -Wall

executable:
    main: Main.hs
