name: deckdeckgo-handler

dependencies:
    - aeson
    - base
    - bytestring
    - case-insensitive
    - deckdeckgo-handler-api
    - directory
    - http-types
    - iproute
    - network
    - servant
    - servant-server
    - temporary
    - text
    - unordered-containers
    - vault
    - wai

ghc-options:
    - -Wall

executable:
    main: Main.hs
