name: deckdeckgo-handler-client

dependencies:
    - aeson
    - base
    - bytestring
    - servant
    - servant-client
    - deckdeckgo-handler-api
    - http-client

ghc-options:
    - -Wall

executable:
    main: Main.hs
